# Generated by Django 2.1.2 on 2018-12-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('published', models.DateTimeField()),
                ('mainImage', models.ImageField(upload_to='images/')),
                ('firstSection', models.TextField(blank=True)),
                ('firstImage', models.ImageField(blank=True, upload_to='images/')),
                ('secondSection', models.TextField(blank=True)),
                ('secondImage', models.ImageField(blank=True, upload_to='images/')),
                ('thirdSection', models.TextField(blank=True)),
                ('thirdImage', models.ImageField(blank=True, upload_to='images/')),
                ('fourthSection', models.TextField(blank=True)),
                ('fourthImage', models.ImageField(blank=True, upload_to='images/')),
                ('fithSection', models.TextField(blank=True)),
                ('fithImage', models.ImageField(blank=True, upload_to='images/')),
                ('summary', models.CharField(max_length=400)),
            ],
        ),
    ]
