# Generated by Django 2.1.2 on 2018-12-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181226_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='firstSection',
            new_name='yourArticleContent',
        ),
        migrations.RemoveField(
            model_name='article',
            name='firstImage',
        ),
        migrations.RemoveField(
            model_name='article',
            name='fithImage',
        ),
        migrations.RemoveField(
            model_name='article',
            name='fithSection',
        ),
        migrations.RemoveField(
            model_name='article',
            name='fithSectionTitile',
        ),
        migrations.RemoveField(
            model_name='article',
            name='fourthImage',
        ),
        migrations.RemoveField(
            model_name='article',
            name='fourthSection',
        ),
        migrations.RemoveField(
            model_name='article',
            name='fourthSectionTitile',
        ),
        migrations.RemoveField(
            model_name='article',
            name='secondImage',
        ),
        migrations.RemoveField(
            model_name='article',
            name='secondSection',
        ),
        migrations.RemoveField(
            model_name='article',
            name='secondSectionTitile',
        ),
        migrations.RemoveField(
            model_name='article',
            name='thirdImage',
        ),
        migrations.RemoveField(
            model_name='article',
            name='thirdSection',
        ),
        migrations.RemoveField(
            model_name='article',
            name='thirdSectionTitile',
        ),
    ]
