# Generated by Django 2.1.2 on 2019-01-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20181227_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome', models.CharField(max_length=200)),
                ('profileImage', models.ImageField(upload_to='images/')),
                ('welcomeMessage', models.TextField(blank=True)),
                ('profileText', models.TextField(blank=True)),
            ],
        ),
    ]
