# Generated by Django 2.1.2 on 2019-01-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_extracontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracontent',
            name='aboutMessage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extracontent',
            name='contactMeMessage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extracontent',
            name='headerImage',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
